name: Trigger On Master
on:
  push:
    branches:
      - master

permissions: 
  contents: write

jobs:
  run-shared:
    uses: ./.github/workflows/build-deb.yaml
    secrets: inherit
  run-ln-msgdef:
    needs: run-shared
    uses: ./.github/workflows/build-ln-msgdef-deb.yaml
    secrets: inherit

